// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"hcrm/backend/internal/app"
	"hcrm/backend/internal/config"
	"hcrm/backend/internal/handler"
	"hcrm/backend/internal/pkg/auth"
	"hcrm/backend/internal/pkg/database"
	"hcrm/backend/internal/pkg/logger"
	"hcrm/backend/internal/repository"
	"hcrm/backend/internal/service"
)

// Injectors from wire.go:

// BuildApp 构建应用（由 Wire 生成实现）
// configPath: 配置文件路径，为空则使用默认路径
func BuildApp(configPath string) (*app.App, func(), error) {
	config, err := provideConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	logConfig := provideLogConfig(config)
	zapLogger, err := logger.New(logConfig)
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := provideDatabaseConfig(config)
	db, cleanup, err := database.NewMySQL(databaseConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := provideRedisConfig(config)
	client, cleanup2, err := database.NewRedis(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	healthRepository := repository.NewHealthRepository(db)
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)
	userRepository := repository.NewUserRepository(db)
	operationLogRepository := repository.NewOperationLogRepository(db)
	loginRateLimiter := auth.NewLoginRateLimiter(client)
	jwtConfig := provideJWTConfig(config)
	jwtHelper := auth.NewJWTHelper(jwtConfig)
	authService := service.NewAuthService(userRepository, operationLogRepository, loginRateLimiter, jwtHelper, client)
	authHandler := handler.NewAuthHandler(authService)
	doctorRepository := repository.NewDoctorRepository(db)
	departmentRepository := repository.NewDepartmentRepository(db)
	titleRepository := repository.NewTitleRepository(db)
	userService := service.NewUserService(userRepository, doctorRepository, departmentRepository, titleRepository)
	userHandler := handler.NewUserHandler(userService)
	roleRepository := repository.NewRoleRepository(db)
	roleService := service.NewRoleService(roleRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	menuRepository := repository.NewMenuRepository(db)
	menuService := service.NewMenuService(menuRepository)
	menuHandler := handler.NewMenuHandler(menuService)
	appApp := app.New(config, zapLogger, db, client, healthHandler, authHandler, userHandler, roleHandler, menuHandler, authService, operationLogRepository, jwtHelper)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// provideConfig 提供配置实例
func provideConfig(configPath string) (*config.Config, error) {
	return config.Load(configPath)
}

func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

func provideLogConfig(cfg *config.Config) *config.LogConfig {
	return &cfg.Log
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}
